# https://github.com/advplyr/audiobookshelf
# https://www.audiobookshelf.org/

# Audiobookshelf is a self-hosted audiobook and podcast server.
name: audiobookshelf
services:
  audiobookshelf:
    container_name: "audiobookshelf"
    image: "ghcr.io/advplyr/audiobookshelf:latest"
    ports:
      - "8065:80"
    restart: "unless-stopped"
    volumes:
      - ./metadata:/metadata
      - ./config:/config
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
    networks:
      - proxy

networks:
  proxy:
    external:
      true
