version: '3.3'
#https://github.com/louislam/uptime-kuma
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
