# https://github.com/OliveTin/OliveTin

# safe and simple access to predefined shell commands from a web interface

name: olivetin

services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    volumes:
      - ./config:/config
    ports:
      - 1337:1337
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
