# https://hub.docker.com/r/adguard/adguardhome
# Network-wide ads & trackers blocking DNS server
name: adguard-home
services:
    adguardhome:
        container_name: adguard-home
        volumes:
            - ./work:/opt/adguardhome/work
            - ./conf:/opt/adguardhome/conf
        ports:
            - 53:53
            - 67:67/udp
            - 68:68/udp
            - 3002:3000
            #- 80:80/tcp
            #- 443:443/tcp
            #- 443:443/udp
        image: adguard/adguardhome
        networks:
            - proxy

networks:
    proxy:
        external: true
