# https://www.portainer.io/

version: '3.3'

name: portainer

services:
  portainer:
    container_name: 'portainer'
    ports:
      - '9000:9000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './portainer_data:/data'
    image: portainer/portainer-ce:latest
    restart: 'unless-stopped'
