name: system-monitoring
services:
  # https://www.influxdata.com/
  influxdb:
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    restart: unless-stopped
    image: influxdb:2.1.1
    networks:
      - proxy
  # https://www.influxdata.com/time-series-platform/telegraf/
  telegraf:
    container_name: telegraf
    image: telegraf:1.25-alpine
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
