# https://github.com/vrtmrz/obsidian-livesync
# Self-hosted LiveSync is a community-implemented synchronization plugin, available on every obsidian-compatible platform and using CouchDB or Object Storage
# http://localhost:5984/_utils/

name: obsidian-livesync
services:
  couchdb:
    image: couchdb:latest
    container_name: obsidian-livesync
    user: 0:0
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=testitest
    volumes:
      - ./data:/opt/couchdb/data
      - ./config/local.ini:/opt/couchdb/etc/local.ini
    # Ports not needed when already passed to Traefik
    ports:
      - 5984:5984
    networks:
      - proxy

networks:
  proxy:
    external: true

