# https://github.com/alexta69/metube

# Web GUI for youtube-dl (using the yt-dlp fork) with playlist support. Allows you to download videos from YouTube and dozens of other sites.

name: metube
services:
  metube:
    networks:
      - proxy
    image: ghcr.io/alexta69/metube
    container_name: metube
    ports:
      - "8088:8081"
    volumes:
      - ./downloads:/downloads

networks:
  proxy:
    external: true
  