---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
    - Plex:
        icon: plex.png
        href: http://localhost:32400
        description: organize, stream, and share your personal media and discover new content from various sources
        siteMonitor: http://plex:32400
        server: my-docker
        container: plex
        # widget:
        #     type: plex
        #     url: 
        #     key: 
    
    - Radarr:
        icon: radarr.png
        href: http://localhost:7878
        description: download movies from various sources and formats
        siteMonitor: http://radarr:7878
        server: my-docker
        container: radarr
        # widget:
        #     type: radarr
        #     url: 
        #     key: 
        #     enableQueue: true

    - Transmission:
        icon: transmission.png
        href: http://localhost:9091
        description:  cross-platform BitTorrent client that integrates with your operating system and behaves like a Mac program
        siteMonitor: http://transmission:9091
        server: my-docker
        container: transmission
        widget:
            type: transmission
            url: http://transmission:9091
            rpcUrl: /transmission/ # Optional. Matches the value of "rpc-url" in your Transmission's settings.json file

- Services:
    - Dawarich:
        icon: si-mapbox-#000000
        href: http://localhost:3007
        description: import your location history from Google Maps Timeline and Owntracks, view it on a map and see some statistics, such as the number of countries and cities visited, and distance traveled
        siteMonitor: http://dawarich:3000
        server: my-docker
        container: dawarich

    - Gramps-Web:
        icon: mdi-family-tree
        href: http://localhost:81
        description: web app for collaborative genealogy
        siteMonitor: http://grampsweb:5000
        server: my-docker
        container: grampsweb

    - Guacamole:
        icon: guacamole.png
        href: http://localhost:80
        description: client-less remote desktop gateway. It supports standard protocols like VNC, RDP, and SSH over HTML5.
        #siteMonitor: http://guacamole:8080
        server: my-docker
        container: guacamole

    - Home Assistant:
        icon: home-assistant.png
        href: http://localhost:8123
        description: versatile and trustworthy smart home hub that integrates with over 1000 brands and runs on various devices
        siteMonitor: http://homeassistant:8123
        server: my-docker
        container: homeassistant
        # widget:
        #     type: homeassistant
        #     url: http://homeassistant:8123
        #     key: 
        #     custom:
        #         - state: sensor.total_power
        #         - state: sensor.total_energy_today
        #           label: energy today
        #         - template: "{{ states.switch|selectattr('state','equalto','on')|list|length }}"
        #           label: switches on
        #         - state: weather.forecast_home
        #           label: wind speed
        #           value: "{attributes.wind_speed} {attributes.wind_speed_unit}"
        
    - Nextcloud:
        icon: nextcloud.png
        href: http://localhost:8080
        description:  self-hosted cloud storage and collaboration software that offers file access, talk, groupware and office integration
        siteMonitor: http://nextcloud:80
        server: my-docker
        container: nextcloud
        # widget:
        #     type: nextcloud
        #     url: 
        #     username: 
        #     password: 

    - Webtrees:
        icon: webtrees.png
        href: http://localhost:86
        description: web-based genealogy application that works from standard GEDCOM files
        siteMonitor: http://webtrees:80
        server: my-docker
        container: webtrees

- Tools:
    - JDownloader:
        icon: jdownloader.png
        href: http://localhost:5800/
        description:  free, open-source download management tool with a huge community that makes downloading as easy and fast as it should be
        siteMonitor: http://jdownloader:5800/
        server: my-docker
        container: jdownloader
        # widget:
        #     type: jdownloader
        #     username: ""
        #     password: ""
        #     client: 

    - MySpeed:
        icon: mdi-speedometer-#232835
        href: http://localhost:5216
        description:  internet speed test
        siteMonitor: http://myspeed:5216
        server: my-docker
        container: myspeed
    
    - OliveTin:
        icon: olivetin.png
        href: http://localhost:1337
        description: safe and simple access to predefined shell commands from a web interface
        siteMonitor: http://olivetin:1337
        server: my-docker
        container: olivetin

    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://localhost:3001
        description:  easy-to-use self-hosted monitoring tool
        siteMonitor: http://uptime-kuma:3001
        server: my-docker
        container: uptime-kuma
        # widget:
        #     type: uptimekuma
        #     url: 
        #     slug:     

    - Whoami:
        icon: mdi-hat-fedora-#000000
        href: http://localhost:84
        description:  simple HTTP server that shows its hostname and IP address
        siteMonitor: http://whoami:80
        server: my-docker
        container: whoami

- Databases:    
    - CockroachDB:
        icon: si-cockroachlabs
        #href: http://localhost:26257
        description:  Port 26257 distributed SQL database built on a transactional and strongly-consistent key-value store
        #siteMonitor: http://cockroachdb:26257
        server: my-docker
        container: cockroachdb
    - CouchDB Obsidian LiveSync:
        icon: si-obsidian-#7C3AED
        href: http://localhost:5984/_utils/
        description:  self-hosted LiveSync is a community-implemented synchronization plugin, available on every obsidian-compatible platform and using CouchDB or Object Storage
        siteMonitor: http://obsidian-livesync:5984/_utils/
        server: my-docker
        container: obsidian-livesync
    - Firebird:
        icon: si-thunderbird-#0A84FF
        #href: http://localhost:3050
        description:  Port 3050 relational database offering many ANSI SQL standard features that runs on Linux, Windows, and a variety of Unix platforms
        #siteMonitor: http://firebird:3050
        server: my-docker
        container: firebird
    - LibSQL:
        icon: si-ardour-#C61C3E
        #href: http://localhost:5001
        description:  Port 5001 SQL Server database that runs on Windows and Linux
        #siteMonitor: http://libsql:5001
        server: my-docker
        container: libsql
    - MariaDB:
        icon: mariadb.png
        #href: http://localhost:3306
        description:  Port 3306 relational database management system that runs on Linux, Windows, and a variety of Unix platforms
        #siteMonitor: http://mariadb:3306
        server: my-docker
        container: mariadb
    - MySQL 8:
        icon: si-mysql-#4479A1
        #href: http://localhost:3308
        description:  Port 3308 relational database management system that runs on Linux, Windows, and a variety of Unix platforms
        #siteMonitor: http://mysql8:3308
        server: my-docker
        container: mysql8
    - PostgreSQL 15:
        icon: si-postgresql-#336791
        #href: http://localhost:5432
        description:  Port 5432 object-relational database system that runs on Linux, Windows, and a variety of Unix platforms
        #siteMonitor: http://postgres:5432
        server: my-docker
        container: postgres15

- Database Clients:
    - Adminer:
        icon: adminer.png
        href: http://localhost:8081
        description: database management in a single PHP file
        #siteMonitor: http://adminer:8081
        server: my-docker
        container: adminer

    - DBGate:
        icon: mdi-database-eye-outline-#2793da
        href: http://localhost:8084
        description:  database manager that supports MySQL, PostgreSQL, SQL Server, SQLite, and MongoDB
        #siteMonitor: http://dbgate:8084
        server: my-docker
        container: dbgate

    - InfluxDB:
        icon: influxdb.png
        href: http://localhost:8086
        description: time-series database designed to handle high write and query loads
        siteMonitor: http://influxdb:8086
        server: my-docker
        container: influxdb

    - PHPmyAdmin:
        icon: phpmyadmin.png
        href: http://localhost:8083
        description:  web-based tool for managing MySQL databases
        #siteMonitor: http://phpmyadmin:8083
        server: my-docker
        container: phpmyadmin

    - SQLChat:
        icon: mdi-robot-excited-#504be2
        href: http://localhost:3005
        description:  chat with your database
        siteMonitor: http://sqlchat:3000
        server: my-docker
        container: sqlchat
    
    - WhoDB:
        icon: mdi-database-eye-#36c1b1
        href: http://localhost:8082
        description:  web-based database management tool
        #siteMonitor: http://whodb:8082
        server: my-docker
        container: whodb

- Server Management:
    - Alpine:
        icon: alpine.png
        description:  lightweight Linux distribution "docker exec -it alpine /bin/sh"
        server: my-docker
        container: alpine
    - Authentik:
        icon: authentik.png
        href: http://localhost:9001
        description:  secure and flexible solution for managing your identity needs
        siteMonitor: http://server:9000
        server: my-docker
        container: authentik-server
        # widget:
        #     type: authentik
        #     url: 
        #     key: 
    - CloudCMD:
        icon: cloudcmd.png
        href: http://localhost:8000
        description: file manager for the web. It includes a command-line console and a text editor
        siteMonitor: http://cloudcmd:8000
        server: my-docker
        container: cloudcmd
    - Grafana-Loki:
        icon: grafana.png
        href: http://localhost:3000
        description:  open-source logging system that does not index the contents of the logs, but rather a set of labels for each log stream
        siteMonitor: http://grafana:3000
        server: my-docker
        container: grafana
        # widget:
        #     type: grafana
        #     url: 
        #     username:
        #     password:

    - VS Code:
        icon: code.png
        href: http://localhost:8443
        description:  VS Code on any machine and access it in the browser
        siteMonitor: http://code-server:8443
        server: my-docker
        container: code-server

- Docker Management:
    - Dockge:
        icon: dockge.png
        href: http://localhost:5002
        description: fancy, easy-to-use and reactive self-hosted docker compose.yaml stack-oriented manager
        siteMonitor: http://dockge:5001
        server: my-docker
        container: dockge

    - Dozzle:
        icon: dozzle.png
        href: http://localhost:8087
        description: web-based application that provides a real-time log viewer for Docker containers
        siteMonitor: http://dozzle:8080
        server: my-docker
        container: dozzle

    - Portainer:
        icon: portainer.png
        href: http://localhost:9000
        description:  versatile container management software that simplifies your secure adoption of containers
        siteMonitor: http://portainer:9000
        server: my-docker
        container: portainer
        # widget:
        #     type: portainer
        #     url: 
        #     env: 
        #     key:    
    
    - Watchtower:
        icon: watchtower.png
        description:  automatically update the running Docker containers
        server: my-docker
        container: watchtower

- Network:
    - Adguard Home:
        icon: adguard-home.png
        href: http://localhost:3002
        description: network-wide ads & trackers blocking DNS server
        siteMonitor: http://adguard-home:3000
        server: my-docker
        container: adguard-home
        # widget:
        #     type: adguardhome
        #     url: http://adguard-home:3002
        #     user:
        #     password:

    - nginx:
        icon: nginx.png
        href: http://localhost:82
        description:  web server that can also be used as a reverse proxy, load balancer, mail proxy, and HTTP cache
        siteMonitor: http://nginx:80
        server: my-docker
        container: nginx

    - Traefik:
        icon: traefik.png
        href: http://localhost:8085
        description: open-source Edge Router that automatically discovers and routes requests to your services
        siteMonitor: http://traefik:8080
        server: my-docker
        container: traefik
        widget:
            type: traefik
            url: http://traefik:8080
