# https://redis.io/

# fast, open source, in-memory data structure store that can also be used as a document or vector database

name: redis

services:
  redis:
    image: docker.io/library/redis:7.2.5
    container_name: redis
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    ports:
      - 6379:6379
    networks:
      - proxy

networks:
  proxy:
    external: true
  